version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_kvv_GHProject
  gitServerName: SIQA_kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: bvt
