version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_kvv_GHProject
  gitServerName: SIQA_kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: bvt
- name: SSL_JDBC_Test
  gitServerName: SIQA_kvv
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqa_kvv_gh.integrations:refdaf
  packages:
  - name: SIQA_kvv_GHProject
    version: "1.0"
- serviceName: project.siqa_kvv_gh.referencedata:ref1
  packages:
  - name: SIQA_kvv_GHProject
    version: "1.0"
